#0:INITIAL
#1:STANDBY(1)
#2:TWO POINTS(6 and 1)
#3:ATTACK_MODE(1,6,7,10)
#4:MULTI_TASK(1,2,3,5,6,10,7,18)
#5:NETWORK
mode: 0

max_command_control_remain_time: 40.0
max_shoot_control_remain_time: 5.0
max_standby_control_remain_time: 5.0 
max_autoaim_control_remain_time: 5.0
max_autoaim_state_control_remain_time: 2.0

pitch_upper_threshold: 8.0
pitch_lower_threshold: -8.0
yaw_work_speed: 0.20
pitch_rotate_speed: 0.10
rotate_freq: 100.0
k_autoaim: 0.2
x_offset: -0.0108
y_offset: 0.002
